apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-backend
  template:
    metadata:
      labels:
        app: mail-backend
    spec:
      containers:
        - name: backend
          image: grim27/mail-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms256m"
          envFrom:
            - configMapRef:
                name: mail-config
            - secretRef:
                name: mail-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mail-backend-service
spec:
  type: ClusterIP
  selector:
    app: mail-backend
  ports:
    - port: 8080
      targetPort: 8080