apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mail-backend
  template:
    metadata:
      labels:
        app: mail-backend
    spec:
      containers:
        - name: backend
          image: grim27/mail-back:5b963324c224090b2c086d8febbcf0d5f26c09f9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mail-config
            - secretRef:
                name: mail-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mail-backend-service
spec:
  type: ClusterIP
  selector:
    app: mail-backend
  ports:
    - port: 8080
      targetPort: 8080