apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  FRONTEND_URL: "http://51.17.68.163"
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "grim27"